#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor DisplayPort-0 -d 1 3 5 7 9
bspc monitor DisplayPort-1 -d 2 4 6 8 10

bspc config border_width        3
bspc config window_gap          8

bspc config normal_border_color "#444444"
bspc config focused_border_color "#888888"

bspc config split_ratio          0.5
bspc config borderless_monocle   true
bspc config gapless_monocle      true

sxhkd -c ~/.config/sxhkd/sxhkdrc &
picom &
feh --bg-fill ~/Pictures/wallpaper.jpg &
xrandr --output DisplayPort-0 --mode 1920x1080 --rate 165 --pos 0x0
xrandr --output DisplayPort-1 --mode 1920x1080 --rate 165 --pos 1920x0
/usr/lib/x86_64-linux-gnu/libexec/polkit-kde-authentication-agent-1 &
killall polybar ;
polybar monitor1 -r &
polybar monitor2 -r &
